//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffDir
{
    using System;
    using System.Collections.Generic;
    
    public partial class wc
    {
        public string First_Name { get; set; }
        public string Preferred_Name { get; set; }
        public string Surname { get; set; }
        public string Employment_Status { get; set; }
        public string Employment_Category { get; set; }
        public string Work_Level { get; set; }
        public string Position_Number { get; set; }
        public string Work_Phone { get; set; }
        public string Phone_Extension { get; set; }
        public string Managers_Number { get; set; }
        public string Managers_Position { get; set; }
        public string Service_Line { get; set; }
        public string Service_Area { get; set; }
        public string Section { get; set; }
        public string Cost_Centre { get; set; }
        public string Location { get; set; }
        public int id { get; set; }
    }
}
